apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - name: api-user
          image: registry.cn-beijing.aliyuncs.com/damondocker/api-user:{version}
          ports:
            - name: http-port
              containerPort: 8764
          env:
            - name: spring_profiles_active
              value: k8s
      imagePullSecrets:
        - name: sba